name: Next Deployment

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH key
        run: |
          echo "=== First 5 lines of SSH key ==="
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -5
          echo "=== End preview ==="

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /baitap-1/deploy-next-docker
            git fetch origin
            git checkout production
            git pull
            docker build -t blog-starter .
            docker stop blog-starter-container || true
            docker rm blog-starter-container || true
            docker run -d -p 4000:3000 --name blog-starter-container blog-starter:latest
